app:
  name: "oms-service"
db:
  host : "localhost"
  port : 5432
  user : "postgres"
  password : "0000"
  name : "rebac"
order:
  load_creation_batch_size: 1000
  processing_batch_size: 10
  processing_interval: 5
  completion_batch_size: 8
  completion_interval: 5
http:
  address : "localhost:9032"
